runtime: nodejs10

service: app

handlers:
  - url: /(.*\.(gif|png|svg|ttf|jpeg|jpg|css|css.map|js|pdf|scss|ico|json|json.map))$
    static_files: build/\1
    secure: always
    upload: build/(.*)
    http_headers:
      X-Frame-Options: deny
  - url: /(.*)
    static_files: build/index.html
    secure: always
    upload: build/index.html
    http_headers:
      X-Frame-Options: deny
